apiVersion: v1
kind: Service
metadata:
  name: achievements
spec:
  selector:
    app: achievements
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.achievements.servicePort }}
      nodePort: {{ .Values.achievements.nodePort }}
  type: NodePort
