apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerprofile
spec:
  replicas: {{ .Values.customerprofile.replicas }}
  selector:
    matchLabels:
      app: customerprofile
  template:
    metadata:
      labels:
        app: customerprofile
    spec:
      containers:
        - name: customerprofile
          image: {{ .Values.customerprofile.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.customerprofile.servicePort }}
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: {{ .Values.global.db.user }}
            - name: DB_PASSWORD
              value: {{ .Values.global.db.password }}
            - name: DB_NAME
              value: {{ .Values.global.db.name }}
