apiVersion: v1
kind: Service
metadata:
  name: customerprofile
spec:
  selector:
    app: customerprofile
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.customerprofile.servicePort }}
      nodePort: {{ .Values.customerprofile.nodePort }}
  type: NodePort
