apiVersion: v1
kind: Service
metadata:
  name: gameprofile
spec:
  selector:
    app: gameprofile
  ports:
    - protocol: TCP
      port: 8081
      targetPort: {{ .Values.gameprofile.servicePort }}
      nodePort: {{ .Values.gameprofile.nodePort }}
  type: NodePort
