apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo
  clusterIP: None