apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: {{ .Values.payments.replicas }}
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: {{ .Values.payments.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.payments.servicePort }}
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: {{ .Values.global.db.user }}
            - name: DB_PASSWORD
              value: {{ .Values.global.db.password }}
            - name: DB_NAME
              value: {{ .Values.global.db.name }}
